routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('users', 'UserController');
Route::resource('activity_log', 'ActivityLogController');

app/ActivityLog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ActivityLog extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ActivityLogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\ActivityLog;

class ActivityLogController extends Controller
{
     public function index(Request $request)
    {
        $filter = $request->get('filter');

        $data = ActivityLog::orderBy('created_at', 'desc');
        $datas = $data->paginate(10);
        
        return view('activity.index', compact('datas'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filter = $request->get('filter');

        $data = User::orderBy('id', 'desc');

        if ($request->has('filter')){
            if (!empty($filter)) {
                $data->where('name', 'like', '%'.$filter.'%');
                $data->orWhere('username', 'like', '%'.$filter.'%');
                $data->orWhere('email', 'like', '%'.$filter.'%');
                $data->orWhere('phone', 'like', '%'.$filter.'%');
                $data->orWhere('address', 'like', '%'.$filter.'%');
            }
        }

        $datas = $data->paginate(10);
        
        return view('users.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.form');
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'password' => 'required|confirmed|min:4',
        ],[
            'password.confirmed' => 'Password dan konfirmasi password tidak sesuai',
        ]);

        DB::beginTransaction();

        try {
            $values = array(
                $request->input('name'),
                $request->input('email'),
                \Hash::make($request->input('password')),
                $request->input('phone'),
                $request->input('address'),
            );
            DB::insert('EXEC proc_insert_user ?, ?, ?, ?, ?', $values);
               

            DB::commit();

            return redirect()->route('users.index')->with('status', 'Successfully created');
        } catch (\Throwable $th) {
            throw $th;

            DB::rollback();
            return redirect()->route('users.create')->with('status', 'FAILED');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function pengguna()
    {
        $user = User::orderBy('id', 'desc')->get();

        return response()->json($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/activity/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Title Header Starts-->
<div class="row page-title-header">
    <div class="col-12">
    <div class="page-header">
        <h4 class="page-title">Log Aktifitas</h4>
        <div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
            <ul class="quick-links ml-auto">
                <li><a href="#">Log Aktifitas</a></li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Page Title Header Ends-->
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Data Log Aktifitas</h4>
                <hr>
                <div class="card-description">
                    <div class="float-left">
                        <a href="{{ url('activity_log') }}" class="btn btn-secondary btnReload" title="Refresh"><i class="mdi mdi-refresh"></i></a>
                    </div>
                    <div class="table-responsive">
                        @if (session('status'))
                            <div class="alert alert-primary alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                                {{ session('status') }}
                            </div>
                        @endif 
                        <hr>
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Deskripsi</th>
                                    <th class="hidden-sm-down" width="80px">Ditambahkan</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($datas as $key => $data)
                                <tr>
                                    <td>{{ $datas->firstItem() + $key }}</td>
                                    <td>{{ $data->activity }}</td>
                                    <td class="hidden-sm-down">
                                        <span>{{ date('H:i:s', strtotime($data->created_at)) }},</span><br>
                                        <span>{{ date('d-M-Y', strtotime($data->created_at)) }}</span>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                {{ $datas->appends(Request::all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Title Header Starts-->
<div class="row page-title-header">
    <div class="col-12">
    <div class="page-header">
        <h4 class="page-title">Dashboard</h4>
        <div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
            <ul class="quick-links ml-auto">
                <li><a href="#">Dashboard</a></li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Page Title Header Ends-->
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="card-description">
                    <h2>Selamat Datang</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- plugins:css -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{{ asset('theme/vendors/iconfonts/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/iconfonts/ionicons/css/ionicons.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/iconfonts/typicons/src/font/typicons.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/css/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/css/vendor.bundle.addons.css') }}">
    <link rel="stylesheet" href="{{ asset('theme/vendors/spinner/jquery-spinner.min.css') }}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ asset('theme/vendors/iconfonts/font-awesome/css/font-awesome.min.css') }}" />
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ asset('theme/css/shared/style.css') }}">
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{{ asset('theme/css/demo_1/style.css') }}">
    
    <link rel="stylesheet" href="{{ asset('theme/css/custom.css') }}">
    <style>
        @media print
        {    
            .no-print, .no-print * {
                display: none !important;
            }

            button, a {
                display: none !important;
            }
        }
    </style>
    @yield('head-extra')
</head>
<body id="mainContainer">

    <div class="container-scroller">
      <!-- partial:partials/_navbar.html -->
      <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row no-print">
        <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
            <a class="navbar-brand brand-logo" style="color:#fff !important" href="/">
                {{ config('app.name') }}
                <!-- <img src="{{ asset('hospicloud-logo-white.png') }}" style="width: 160px;" alt="logo"> -->
            </a>
            <a class="navbar-brand brand-logo-mini" href="/">
                <img src="{{ asset('favicon.png') }}" style="width: 40px;" alt="logo">
            </a>
        </div>

      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas no-print" id="sidebar">
            <ul class="nav">
                <li class="nav-item nav-profile">
                    <a href="#" class="nav-link" style="height: auto;">
                        <div class="profile-image">
                            <i class="fa fa-2x fa-user-circle"></i>
                        </div>
                        <div class="text-wrapper">
                            <p class="profile-name">Welcome</p>
                            <p class="designation text-xs"><span class="d-block mb-1">Selamat Datang</small></p>
                        </div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('home') }}">
                        <i class="menu-icon typcn typcn-document-text"></i>
                        <span class="menu-title">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url('users') }}">
                        <i class="menu-icon typcn typcn-shopping-bag"></i>
                        <span class="menu-title">User</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url('activity_log') }}">
                        <i class="menu-icon typcn typcn-shopping-bag"></i>
                        <span class="menu-title">Log Aktifitas</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- partial -->
        <div class="main-panel">
            <div class="content-wrapper">
                @yield('content')
            </div>
            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            <footer class="footer">
                <div class="container-fluid clearfix">
                    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">{{config('app.name')}}</span>
                    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"><i>Zulfakhri | 2021 </i> 
                    </span>
                </div>
            </footer>
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{{ asset('theme/vendors/js/vendor.bundle.base.js') }}"></script>
    <script src="{{ asset('theme/vendors/js/vendor.bundle.addons.js') }}"></script>
    <script src="{{ asset('theme/vendors/spinner/jquery-spinner.min.js') }}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{{ asset('theme/js/shared/off-canvas.js') }}"></script>
    <script src="{{ asset('theme/js/shared/misc.js') }}"></script>
    <!-- endinject -->
    <script src="{{ asset('theme/js/demo_1/dashboard.js') }}"></script>
    <script src="{{ asset('js/custom.js') }}"></script>
    <!-- End custom js for this page-->
    <script type="text/javascript">
        const spinner = new jQuerySpinner({ parentId: 'mainContainer' });
        spinner.show();
        $(document).ready(function() { spinner.hide(); });
    </script>
    @yield('end-script')
</body>
</html>

resources/views/users/detail.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Title Header Starts-->
<div class="row page-title-header">
    <div class="col-12">
    <div class="page-header">
        <h4 class="page-title">User</h4>
        <div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
            <ul class="quick-links ml-auto">
                <li><a href="#">Master Data</a></li>
                <li><a href="#">User Akses</a></li>
                <li><a href="#">Detail</a></li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Page Title Header Ends-->
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Detail User Akses</h4>
                <hr>
                <div class="card-description">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <b for="name">Nama : </b>
                                <p>{{ $user->name ?? '-' }}</p>
                            </div>
                            <div class="form-group">
                                <b for="username">Username : </b>
                                <p>{{ $user->username ?? '-' }}</p>
                            </div>
                            <div class="form-group">
                                <b for="email">Email : </b>
                                <p>{{ $user->email ?? '-' }}</p>
                            </div>
                            <div class="form-group">
                                <b for="phone">Telp : </b>
                                <p>{{ $user->phone ?? '-' }}</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <b for="address">Alamat : </b>
                                <p>{{ $user->address ?? '-' }}</p>
                            </div>
                            <div class="form-group">
                                <b for="roles">Hak Akses : </b>
                                <p>@foreach ($user->roles as $k => $role){{ $role->name }},@endforeach</p>
                            </div>
                            <div class="form-group">
                                <b for="status">status : </b>
                                @if ($user->status == 0)
                                    <p><label class="badge badge-success">Aktif</label></p>
                                @elseif ($user->status == 1)
                                    <p><label class="badge badge-warning">NonAktif</label></p>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">
                            <br>
                            <a href="{{ url('masters/users') }}" class="btn btn-primary btn-fw"><i class="mdi mdi-arrow-left text-white"></i> Kembali</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/form.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Title Header Starts-->
<div class="row page-title-header">
    <div class="col-12">
    <div class="page-header">
        <h4 class="page-title">User</h4>
        <div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
            <ul class="quick-links ml-auto">
                <li><a href="#">User</a></li>
                <li><a href="#">Form</a></li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Page Title Header Ends-->
<div class="row">
    <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Form @if(!empty($user)){{ 'Edit' }}@else{{ 'Tambah' }}@endif Data</h4>
                        <hr>
                        <form class="forms-sample" enctype="multipart/form-data" action="@if(!empty($user)) {{ route('users.update', [$user->uuid]) }} @else {{ route('users.store') }} @endif" method="POST">
                            @csrf
                            @if(!empty($user))
                                <input type="hidden" value="PUT" name="_method">
                            @endif
                            <div class="row">
                                @if (session('status'))
                                <div class="col-md-12">
                                    <div class="alert alert-warning">
                                        {{ session('status') }}
                                    </div>
                                </div>
                                @endif 
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Nama</label>
                                        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name" placeholder="Nama Lengkap" value="@if(!empty($user)){{ $user->name }}@else{{ old('name') }}@endif">
                                        @error('name')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                    
                                    <div class="form-group">
                                        <label for="phone">Telp</label>
                                        <input type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" id="phone" placeholder="Telp" value="@if(!empty($user)){{ $user->phone }}@else{{ old('phone') }}@endif">
                                        @error('phone')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="address">Alamat</label>
                                        <input type="text" class="form-control @error('address') is-invalid @enderror" name="address" id="address" placeholder="Alamat" value="@if(!empty($user)){{ $user->address }}@else{{ old('address') }}@endif">
                                        @error('address')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control @error('email') is-invalid @enderror" name="email" id="email" placeholder="Email" value="@if(!empty($user)){{ $user->email }}@else{{ old('email') }}@endif">
                                        @error('email')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" placeholder="Password" >
                                        @error('password')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="password_confirmation">Konfirmasi Password</label>
                                        <input type="password" class="form-control @error('password_confirmation') is-invalid @enderror" name="password_confirmation" id="password_confirmation" placeholder="Konfirmasi Password" >
                                        @error('password_confirmation')<div class="invalid-feedback">* {{ $message }}</div>@enderror
                                    </div>
                                </div>
                            </div>
                            <a href="{{ url('users') }}" class="btn btn-danger">Batal</a>
                            <button type="submit" class="btn btn-success float-right">Simpan</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Page Title Header Starts-->
<div class="row page-title-header">
    <div class="col-12">
    <div class="page-header">
        <h4 class="page-title">User</h4>
        <div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">
            <ul class="quick-links ml-auto">
                <li><a href="#">User</a></li>
            </ul>
        </div>
    </div>
    </div>
</div>
<!-- Page Title Header Ends-->
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Data User</h4>
                <hr>
                <div class="card-description">
                    <div class="float-left">
                        <a href="{{ url('users') }}" class="btn btn-secondary btnReload" title="Refresh"><i class="mdi mdi-refresh"></i></a>
                        <a href="{{ url('users/create') }}" class="btn btn-primary btn-fw"><i class="mdi mdi-plus-outline text-white"></i> Tambah Data</a>
                    </div>
                    <div class="float-right">
                        <form method="GET" action="{{ url('users') }}">
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" name="filter" id="filter" value="{{ Request::get('filter') }}" class="form-control" placeholder="Pencarian" aria-label="Pencarian" aria-describedby="colored-addon3">
                                    <div class="input-group-append bg-primary border-primary">
                                        <button type="submit" class="input-group-text bg-transparent"><i class="mdi mdi-magnify text-white"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="table-responsive">
                        @if (session('status'))
                            <div class="alert alert-primary alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                                {{ session('status') }}
                            </div>
                        @endif 
                        <table class="table table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th class="hidden-sm-down">Info</th>
                                    <th class="hidden-sm-down" width="80px">Ditambahkan</th>
                                    <th class="btnAction">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($datas as $key => $data)
                                <tr>
                                    <td>{{ $datas->firstItem() + $key }}</td>
                                    <td>{{ $data->name }}</td>
                                    <td class="hidden-sm-down">
                                        <small>
                                            <b>Telp : </b> {{ $data->phone ?? '-' }}<br>
                                            <b>Email : </b> {{ $data->email ?? '-' }}<br>
                                            <b>Alamat : </b> {{ $data->address ?? '-' }}
                                        </small>
                                    </td>
                                    <td class="hidden-sm-down">
                                        <span>{{ date('H:i:s', strtotime($data->created_at)) }},</span><br>
                                        <span>{{ date('d-M-Y', strtotime($data->created_at)) }}</span>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Aksi </button>
                                            <div class="dropdown-menu" x-placement="bottom-start">
                                                <a class="dropdown-item" href="{{ route('users.edit', [$data->id]) }}">Edit</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('delete-form-{{ $data->id }}').submit();">Hapus</a>
                                            </div>
                                        </div>
                                        @if($data->id != 1)
                                        <form id="delete-form-{{ $data->id }}" onsubmit="return confirm('Delete data?')" class="d-inline invisible" action="{{ route('users.destroy', [$data->id]) }}" method="POST">
                                            @csrf
                                            <input type="hidden" name="_method" value="DELETE">
                                            <button type="submit" class="btn btn-danger text-white btn-sm invisible" title="Hapus"><i class="fas fa-trash"></i></button>
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card-footer text-right">
                {{ $datas->appends(Request::all())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection